# SPDX-License-Identifier: MIT-0
---
# tasks file for db

- name: Install acl for become_user compatibility
  become: true
  apt:
    name: acl
    state: present
    update_cache: true

- name: Install psycopg2 for Ansible PostgreSQL modules
  become: true
  apt:
    name: python3-psycopg2
    state: present

- name: Install PostgreSQL server
  become: true
  package:
    name: postgresql
    state: present

- name: Allow PostgreSQL to listen on all interfaces
  become: true
  lineinfile:
    path: /etc/postgresql/14/main/postgresql.conf
    regexp: "^#?listen_addresses =.*"
    line: "listen_addresses = '*'"
  notify: Restart PostgreSQL

- name: Allow connections from private subnet in pg_hba.conf
  become: true
  lineinfile:
    path: /etc/postgresql/14/main/pg_hba.conf
    line: "host    all             all             10.0.0.0/16            md5"
    insertafter: EOF
  notify: Restart PostgreSQL


- name: Ensure PostgreSQL is started and enabled
  become: true
  service:
    name: postgresql
    state: started
    enabled: true



- name: Ensure PostgreSQL user 'django' exists with password
  become: true
  become_user: postgres
  postgresql_user:
    name: django
    password: django123
    encrypted: false
    state: present

- name: Ensure PostgreSQL database 'sample' exists owned by 'django'
  become: true
  become_user: postgres
  postgresql_db:
    name: sample
    owner: django
    state: present
